export default [
  {
    title: "Full-Stack Engineer",
    company: "Toggle Industries",
    location: "Remote",
    range: "November 2021 - Present",
    link: "https://toggle.build/",
    bullets: [
      `Designed and implemented a real-time manufacturing system interfacing with industrial machinery, optimizing latency-critical workflows using multithreaded programming and performance profiling.`,
      `Engineered a distributed architecture for processing architectural plans and robotic motion planning, emphasizing low-latency communication and crash tolerance.`,
      `Built out CRM with document generation for billing, shipping, and tagging of rebar assemblies for commerce & logistics.`,
      `Conducted user interviews to direct new software feature design and bug fixes.`,
      `Second software hire; communicated with founders on a weekly basis in a team spread across 9 timezones.`,
      `Sole developer for final 10 months re-architected the in-house robotics software stack, migrating its core framework to ROS, for a startup that secured $3M in seed funding and an $8M Series A.`,
      `Worked with Typescript, React, Go, Docker, gRPC, PostgreSQL, CI/CD, Redis, Playwright, TailwindCSS, Bash, Linux, and more.`,
    ],
  },
  {
    title: "Full-Stack Engineer",
    company: "Mcity",
    location: "Ann Arbor, MI",
    range: "March 2020 - September 2021",
    link: "https://www.mcity.umich.edu/",
    bullets: [
      `Developed research tools for the world’s largest connected & autonomous vehicle test environment. Used by Ford, GM, Toyota, Subaru, and BMW autonomous vehicle researchers among others.`,
      `Integrated websockets for live data streaming, ensuring sub-100ms latency.`,
      `Built a proximity-aware network visualization tool for autonomous vehicle testing, achieving 6300% faster device connectivity analysis through efficient data structures and real-time event handling.`,
      `Modernized legacy systems by refactoring monolithic codebases into modular components, improving maintainability.`,
      `Implemented unit test and integration test suites hooked into CI/CD pipelines.`,
      `Worked with Javascript, Vue, Python, Flask, Docker, PostgreSQL, Redis, Linux, and more.`,
    ],
  },
  {
    title: "Assistant Researcher",
    company: "ArtsEngine",
    location: "Ann Arbor, MI",
    range: "October 2017 — June 2020",
    link: "https://artsengine.engin.umich.edu/",
    bullets: [
      `Described, summarized, and interpreted unstructured and structured data using various statistical models, natural language processing tools, text embeddings, and plotting libraries in R.`,
      `Conceptualized statistical analysis workflows, and designed integral visualization and decision support tools.`,
      `Instrumental in fulfilling deliverables or several national and local grants, as well as national policy-level talks and discussion.`,
      `Experience with cluster analysis, topic modeling, random forests, large longitudinal survey data, consulting with statistics doctorates, etc. to solve real problems and gain new insights.`,
      `Worked with R, Tidyverse, Machine Learning, NLP, D3, Javascript, Linux, and more.`,
    ],
  },
];
